### ISSUE TITLE
Disconnect from Carpentries and Google calendar, add Timezone and end time

### ISSUE THREAD

**Issue by liekelotte** [esciencecenter-digital-skills/esciencecenter-digital-skills.github.io#19]
1. The Google Calendar link tends not to work, so we don't include it, generally. 
2. This is not a carpentries workshop, so "contact the carpentries" should be removed in the footer
3. Code of conduct tab should be removed at the top
4. Add the timezone (CEST)
5. Add the end time for each day (1pm)

Sorry about these nitpicky things and thank you!!

**Comment by mkuzak** [comment]
@liekelotte  I think those issues are for the workshop template.
I think we address them in the next workshop template.
