### ISSUE TITLE
Old link in README

### ISSUE THREAD

**Issue by CunliangGeng** [esciencecenter-digital-skills/esciencecenter-digital-skills.github.io#27]
In the README there is such a link 
`[repository settings](https://github.com/escience-academy/escience-academy.github.io/settings).`
it can be automatically redirected to `https://github.com/esciencecenter-digital-skills/esciencecenter-digital-skills.github.io/settings` which however is a 404 page.

I have no idea how to fix it, maybe it's because I don't have access to the `settings` page.

**Comment by mkuzak** [comment]
Hello @CunliangGeng thank you for reporting this. I updated the URL
